/** Rótulos das ações de auditoria (seguro para o bundle do cliente). */
export const AUDIT_ACTION_LABEL: Record<string, string> = {
  assessment_viewed: "Acessou uma triagem",
  assessment_submitted: "Triagem enviada pelo paciente",
  report_exported: "Baixou relatório em PDF",
  contact_created: "Cadastrou um contato",
  invite_created: "Gerou convite de triagem",
  whatsapp_sent: "Enviou mensagem por WhatsApp",
  invite_resent: "Reenviou o questionário por WhatsApp",
  note_added: "Registrou parecer médico",
  email_sent: "E-mail de resultados enviado",
  email_failed: "Falha no envio de e-mail",
  whatsapp_result_notice: "Aviso de resultados por WhatsApp",
  doctor_profile_saved: "Salvou o perfil público de um médico",
  doctor_profile_removed: "Removeu o perfil público de um médico",
  portal_patient_view: "Paciente viu o próprio resumo no portal",
  subscription_created: "Criou a assinatura de um consultório",
  subscription_updated: "Atualizou a assinatura de um consultório",
  outcome_recorded: "Registrou o desfecho clínico de uma triagem",
  research_settings_updated: "Alterou a configuração de pesquisa de uma clínica",
  research_export: "Exportou o conjunto de dados de pesquisa (anonimizado)",
  research_consent_withdrawn: "Retirou o consentimento de pesquisa de um titular",
};
