/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriagemRouteImport } from './routes/triagem'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as AuthenticatedSenhaRouteImport } from './routes/_authenticated/senha'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedResumoRouteImport } from './routes/_authenticated/resumo'
import { Route as AuthenticatedReferenciasRouteImport } from './routes/_authenticated/referencias'
import { Route as AuthenticatedProtocoloRouteImport } from './routes/_authenticated/protocolo'
import { Route as AuthenticatedOcupacionalRouteImport } from './routes/_authenticated/ocupacional'
import { Route as AuthenticatedMetaLandingRouteImport } from './routes/_authenticated/meta-landing'
import { Route as AuthenticatedMateriaisRouteImport } from './routes/_authenticated/materiais'
import { Route as AuthenticatedInterpretarRouteImport } from './routes/_authenticated/interpretar'
import { Route as AuthenticatedEvolucaoRouteImport } from './routes/_authenticated/evolucao'
import { Route as AuthenticatedEmailsRouteImport } from './routes/_authenticated/emails'
import { Route as AuthenticatedContatosRouteImport } from './routes/_authenticated/contatos'
import { Route as AuthenticatedComercialRouteImport } from './routes/_authenticated/comercial'
import { Route as AuthenticatedChangelogRouteImport } from './routes/_authenticated/changelog'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAjudaRouteImport } from './routes/_authenticated/ajuda'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as SlugTriagemRouteImport } from './routes/$slug.triagem'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as ApiPublicOgLandingRouteImport } from './routes/api/public/og-landing'
import { Route as ApiPublicClinicAssetRouteImport } from './routes/api/public/clinic-asset'
import { Route as AuthenticatedPainelIdRouteImport } from './routes/_authenticated/painel.$id'

const TriagemRoute = TriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const AuthenticatedSenhaRoute = AuthenticatedSenhaRouteImport.update({
  id: '/senha',
  path: '/senha',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumoRoute = AuthenticatedResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferenciasRoute =
  AuthenticatedReferenciasRouteImport.update({
    id: '/referencias',
    path: '/referencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProtocoloRoute = AuthenticatedProtocoloRouteImport.update({
  id: '/protocolo',
  path: '/protocolo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOcupacionalRoute =
  AuthenticatedOcupacionalRouteImport.update({
    id: '/ocupacional',
    path: '/ocupacional',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetaLandingRoute =
  AuthenticatedMetaLandingRouteImport.update({
    id: '/meta-landing',
    path: '/meta-landing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMateriaisRoute = AuthenticatedMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterpretarRoute =
  AuthenticatedInterpretarRouteImport.update({
    id: '/interpretar',
    path: '/interpretar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvolucaoRoute = AuthenticatedEvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailsRoute = AuthenticatedEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContatosRoute = AuthenticatedContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComercialRoute = AuthenticatedComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangelogRoute = AuthenticatedChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjudaRoute = AuthenticatedAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SlugTriagemRoute = SlugTriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => SlugRoute,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/painel/',
    path: '/painel/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicOgLandingRoute = ApiPublicOgLandingRouteImport.update({
  id: '/api/public/og-landing',
  path: '/api/public/og-landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClinicAssetRoute = ApiPublicClinicAssetRouteImport.update({
  id: '/api/public/clinic-asset',
  path: '/api/public/clinic-asset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelIdRoute = AuthenticatedPainelIdRouteImport.update({
  id: '/painel/$id',
  path: '/painel/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/auth': typeof AuthRoute
  '/entrar': typeof EntrarRoute
  '/portal': typeof PortalRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/triagem': typeof TriagemRoute
  '/$slug/triagem': typeof SlugTriagemRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/evolucao': typeof AuthenticatedEvolucaoRoute
  '/interpretar': typeof AuthenticatedInterpretarRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/meta-landing': typeof AuthenticatedMetaLandingRoute
  '/ocupacional': typeof AuthenticatedOcupacionalRoute
  '/protocolo': typeof AuthenticatedProtocoloRoute
  '/referencias': typeof AuthenticatedReferenciasRoute
  '/resumo': typeof AuthenticatedResumoRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/senha': typeof AuthenticatedSenhaRoute
  '/$slug/': typeof SlugIndexRoute
  '/painel/$id': typeof AuthenticatedPainelIdRoute
  '/api/public/clinic-asset': typeof ApiPublicClinicAssetRoute
  '/api/public/og-landing': typeof ApiPublicOgLandingRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/entrar': typeof EntrarRoute
  '/portal': typeof PortalRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/triagem': typeof TriagemRoute
  '/$slug/triagem': typeof SlugTriagemRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/evolucao': typeof AuthenticatedEvolucaoRoute
  '/interpretar': typeof AuthenticatedInterpretarRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/meta-landing': typeof AuthenticatedMetaLandingRoute
  '/ocupacional': typeof AuthenticatedOcupacionalRoute
  '/protocolo': typeof AuthenticatedProtocoloRoute
  '/referencias': typeof AuthenticatedReferenciasRoute
  '/resumo': typeof AuthenticatedResumoRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/senha': typeof AuthenticatedSenhaRoute
  '/$slug': typeof SlugIndexRoute
  '/painel/$id': typeof AuthenticatedPainelIdRoute
  '/api/public/clinic-asset': typeof ApiPublicClinicAssetRoute
  '/api/public/og-landing': typeof ApiPublicOgLandingRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRouteWithChildren
  '/auth': typeof AuthRoute
  '/entrar': typeof EntrarRoute
  '/portal': typeof PortalRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/triagem': typeof TriagemRoute
  '/$slug/triagem': typeof SlugTriagemRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ajuda': typeof AuthenticatedAjudaRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/changelog': typeof AuthenticatedChangelogRoute
  '/_authenticated/comercial': typeof AuthenticatedComercialRoute
  '/_authenticated/contatos': typeof AuthenticatedContatosRoute
  '/_authenticated/emails': typeof AuthenticatedEmailsRoute
  '/_authenticated/evolucao': typeof AuthenticatedEvolucaoRoute
  '/_authenticated/interpretar': typeof AuthenticatedInterpretarRoute
  '/_authenticated/materiais': typeof AuthenticatedMateriaisRoute
  '/_authenticated/meta-landing': typeof AuthenticatedMetaLandingRoute
  '/_authenticated/ocupacional': typeof AuthenticatedOcupacionalRoute
  '/_authenticated/protocolo': typeof AuthenticatedProtocoloRoute
  '/_authenticated/referencias': typeof AuthenticatedReferenciasRoute
  '/_authenticated/resumo': typeof AuthenticatedResumoRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/senha': typeof AuthenticatedSenhaRoute
  '/$slug/': typeof SlugIndexRoute
  '/_authenticated/painel/$id': typeof AuthenticatedPainelIdRoute
  '/api/public/clinic-asset': typeof ApiPublicClinicAssetRoute
  '/api/public/og-landing': typeof ApiPublicOgLandingRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/entrar'
    | '/portal'
    | '/primeiro-acesso'
    | '/reset-password'
    | '/triagem'
    | '/$slug/triagem'
    | '/admin'
    | '/ajuda'
    | '/auditoria'
    | '/changelog'
    | '/comercial'
    | '/contatos'
    | '/emails'
    | '/evolucao'
    | '/interpretar'
    | '/materiais'
    | '/meta-landing'
    | '/ocupacional'
    | '/protocolo'
    | '/referencias'
    | '/resumo'
    | '/roadmap'
    | '/senha'
    | '/$slug/'
    | '/painel/$id'
    | '/api/public/clinic-asset'
    | '/api/public/og-landing'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/entrar'
    | '/portal'
    | '/primeiro-acesso'
    | '/reset-password'
    | '/triagem'
    | '/$slug/triagem'
    | '/admin'
    | '/ajuda'
    | '/auditoria'
    | '/changelog'
    | '/comercial'
    | '/contatos'
    | '/emails'
    | '/evolucao'
    | '/interpretar'
    | '/materiais'
    | '/meta-landing'
    | '/ocupacional'
    | '/protocolo'
    | '/referencias'
    | '/resumo'
    | '/roadmap'
    | '/senha'
    | '/$slug'
    | '/painel/$id'
    | '/api/public/clinic-asset'
    | '/api/public/og-landing'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/auth'
    | '/entrar'
    | '/portal'
    | '/primeiro-acesso'
    | '/reset-password'
    | '/triagem'
    | '/$slug/triagem'
    | '/_authenticated/admin'
    | '/_authenticated/ajuda'
    | '/_authenticated/auditoria'
    | '/_authenticated/changelog'
    | '/_authenticated/comercial'
    | '/_authenticated/contatos'
    | '/_authenticated/emails'
    | '/_authenticated/evolucao'
    | '/_authenticated/interpretar'
    | '/_authenticated/materiais'
    | '/_authenticated/meta-landing'
    | '/_authenticated/ocupacional'
    | '/_authenticated/protocolo'
    | '/_authenticated/referencias'
    | '/_authenticated/resumo'
    | '/_authenticated/roadmap'
    | '/_authenticated/senha'
    | '/$slug/'
    | '/_authenticated/painel/$id'
    | '/api/public/clinic-asset'
    | '/api/public/og-landing'
    | '/_authenticated/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRouteWithChildren
  AuthRoute: typeof AuthRoute
  EntrarRoute: typeof EntrarRoute
  PortalRoute: typeof PortalRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TriagemRoute: typeof TriagemRoute
  ApiPublicClinicAssetRoute: typeof ApiPublicClinicAssetRoute
  ApiPublicOgLandingRoute: typeof ApiPublicOgLandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triagem': {
      id: '/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof TriagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/_authenticated/senha': {
      id: '/_authenticated/senha'
      path: '/senha'
      fullPath: '/senha'
      preLoaderRoute: typeof AuthenticatedSenhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumo': {
      id: '/_authenticated/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof AuthenticatedResumoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referencias': {
      id: '/_authenticated/referencias'
      path: '/referencias'
      fullPath: '/referencias'
      preLoaderRoute: typeof AuthenticatedReferenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/protocolo': {
      id: '/_authenticated/protocolo'
      path: '/protocolo'
      fullPath: '/protocolo'
      preLoaderRoute: typeof AuthenticatedProtocoloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocupacional': {
      id: '/_authenticated/ocupacional'
      path: '/ocupacional'
      fullPath: '/ocupacional'
      preLoaderRoute: typeof AuthenticatedOcupacionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meta-landing': {
      id: '/_authenticated/meta-landing'
      path: '/meta-landing'
      fullPath: '/meta-landing'
      preLoaderRoute: typeof AuthenticatedMetaLandingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiais': {
      id: '/_authenticated/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof AuthenticatedMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interpretar': {
      id: '/_authenticated/interpretar'
      path: '/interpretar'
      fullPath: '/interpretar'
      preLoaderRoute: typeof AuthenticatedInterpretarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evolucao': {
      id: '/_authenticated/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof AuthenticatedEvolucaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emails': {
      id: '/_authenticated/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AuthenticatedEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contatos': {
      id: '/_authenticated/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AuthenticatedContatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comercial': {
      id: '/_authenticated/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AuthenticatedComercialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/changelog': {
      id: '/_authenticated/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AuthenticatedChangelogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajuda': {
      id: '/_authenticated/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AuthenticatedAjudaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$slug/triagem': {
      id: '/$slug/triagem'
      path: '/triagem'
      fullPath: '/$slug/triagem'
      preLoaderRoute: typeof SlugTriagemRouteImport
      parentRoute: typeof SlugRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/og-landing': {
      id: '/api/public/og-landing'
      path: '/api/public/og-landing'
      fullPath: '/api/public/og-landing'
      preLoaderRoute: typeof ApiPublicOgLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clinic-asset': {
      id: '/api/public/clinic-asset'
      path: '/api/public/clinic-asset'
      fullPath: '/api/public/clinic-asset'
      preLoaderRoute: typeof ApiPublicClinicAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/$id': {
      id: '/_authenticated/painel/$id'
      path: '/painel/$id'
      fullPath: '/painel/$id'
      preLoaderRoute: typeof AuthenticatedPainelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAjudaRoute: typeof AuthenticatedAjudaRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedChangelogRoute: typeof AuthenticatedChangelogRoute
  AuthenticatedComercialRoute: typeof AuthenticatedComercialRoute
  AuthenticatedContatosRoute: typeof AuthenticatedContatosRoute
  AuthenticatedEmailsRoute: typeof AuthenticatedEmailsRoute
  AuthenticatedEvolucaoRoute: typeof AuthenticatedEvolucaoRoute
  AuthenticatedInterpretarRoute: typeof AuthenticatedInterpretarRoute
  AuthenticatedMateriaisRoute: typeof AuthenticatedMateriaisRoute
  AuthenticatedMetaLandingRoute: typeof AuthenticatedMetaLandingRoute
  AuthenticatedOcupacionalRoute: typeof AuthenticatedOcupacionalRoute
  AuthenticatedProtocoloRoute: typeof AuthenticatedProtocoloRoute
  AuthenticatedReferenciasRoute: typeof AuthenticatedReferenciasRoute
  AuthenticatedResumoRoute: typeof AuthenticatedResumoRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSenhaRoute: typeof AuthenticatedSenhaRoute
  AuthenticatedPainelIdRoute: typeof AuthenticatedPainelIdRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAjudaRoute: AuthenticatedAjudaRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedChangelogRoute: AuthenticatedChangelogRoute,
  AuthenticatedComercialRoute: AuthenticatedComercialRoute,
  AuthenticatedContatosRoute: AuthenticatedContatosRoute,
  AuthenticatedEmailsRoute: AuthenticatedEmailsRoute,
  AuthenticatedEvolucaoRoute: AuthenticatedEvolucaoRoute,
  AuthenticatedInterpretarRoute: AuthenticatedInterpretarRoute,
  AuthenticatedMateriaisRoute: AuthenticatedMateriaisRoute,
  AuthenticatedMetaLandingRoute: AuthenticatedMetaLandingRoute,
  AuthenticatedOcupacionalRoute: AuthenticatedOcupacionalRoute,
  AuthenticatedProtocoloRoute: AuthenticatedProtocoloRoute,
  AuthenticatedReferenciasRoute: AuthenticatedReferenciasRoute,
  AuthenticatedResumoRoute: AuthenticatedResumoRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSenhaRoute: AuthenticatedSenhaRoute,
  AuthenticatedPainelIdRoute: AuthenticatedPainelIdRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SlugRouteChildren {
  SlugTriagemRoute: typeof SlugTriagemRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugTriagemRoute: SlugTriagemRoute,
  SlugIndexRoute: SlugIndexRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRouteWithChildren,
  AuthRoute: AuthRoute,
  EntrarRoute: EntrarRoute,
  PortalRoute: PortalRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TriagemRoute: TriagemRoute,
  ApiPublicClinicAssetRoute: ApiPublicClinicAssetRoute,
  ApiPublicOgLandingRoute: ApiPublicOgLandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
